################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../dronecan/src/dronecan.protocol.CanStats.c \
../dronecan/src/dronecan.protocol.FlexDebug.c \
../dronecan/src/dronecan.protocol.Stats.c \
../dronecan/src/dronecan.remoteid.ArmStatus.c \
../dronecan/src/dronecan.remoteid.BasicID.c \
../dronecan/src/dronecan.remoteid.Location.c \
../dronecan/src/dronecan.remoteid.OperatorID.c \
../dronecan/src/dronecan.remoteid.SecureCommand_req.c \
../dronecan/src/dronecan.remoteid.SecureCommand_res.c \
../dronecan/src/dronecan.remoteid.SelfID.c \
../dronecan/src/dronecan.remoteid.System.c \
../dronecan/src/dronecan.sensors.hygrometer.Hygrometer.c \
../dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.c \
../dronecan/src/dronecan.sensors.rc.RCInput.c \
../dronecan/src/dronecan.sensors.rpm.RPM.c \
../dronecan/src/uavcan.CoarseOrientation.c \
../dronecan/src/uavcan.Timestamp.c \
../dronecan/src/uavcan.equipment.actuator.ArrayCommand.c \
../dronecan/src/uavcan.equipment.actuator.Command.c \
../dronecan/src/uavcan.equipment.actuator.Status.c \
../dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.c \
../dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.c \
../dronecan/src/uavcan.equipment.ahrs.RawIMU.c \
../dronecan/src/uavcan.equipment.ahrs.Solution.c \
../dronecan/src/uavcan.equipment.air_data.AngleOfAttack.c \
../dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.c \
../dronecan/src/uavcan.equipment.air_data.RawAirData.c \
../dronecan/src/uavcan.equipment.air_data.Sideslip.c \
../dronecan/src/uavcan.equipment.air_data.StaticPressure.c \
../dronecan/src/uavcan.equipment.air_data.StaticTemperature.c \
../dronecan/src/uavcan.equipment.air_data.TrueAirspeed.c \
../dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.c \
../dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.c \
../dronecan/src/uavcan.equipment.camera_gimbal.Mode.c \
../dronecan/src/uavcan.equipment.camera_gimbal.Status.c \
../dronecan/src/uavcan.equipment.device.Temperature.c \
../dronecan/src/uavcan.equipment.esc.RPMCommand.c \
../dronecan/src/uavcan.equipment.esc.RawCommand.c \
../dronecan/src/uavcan.equipment.esc.Status.c \
../dronecan/src/uavcan.equipment.esc.StatusExtended.c \
../dronecan/src/uavcan.equipment.gnss.Auxiliary.c \
../dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.c \
../dronecan/src/uavcan.equipment.gnss.Fix.c \
../dronecan/src/uavcan.equipment.gnss.Fix2.c \
../dronecan/src/uavcan.equipment.gnss.RTCMStream.c \
../dronecan/src/uavcan.equipment.hardpoint.Command.c \
../dronecan/src/uavcan.equipment.hardpoint.Status.c \
../dronecan/src/uavcan.equipment.ice.FuelTankStatus.c \
../dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.c \
../dronecan/src/uavcan.equipment.ice.reciprocating.Status.c \
../dronecan/src/uavcan.equipment.indication.BeepCommand.c \
../dronecan/src/uavcan.equipment.indication.LightsCommand.c \
../dronecan/src/uavcan.equipment.indication.RGB565.c \
../dronecan/src/uavcan.equipment.indication.SingleLightCommand.c \
../dronecan/src/uavcan.equipment.power.BatteryInfo.c \
../dronecan/src/uavcan.equipment.power.CircuitStatus.c \
../dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.c \
../dronecan/src/uavcan.equipment.range_sensor.Measurement.c \
../dronecan/src/uavcan.equipment.safety.ArmingStatus.c \
../dronecan/src/uavcan.navigation.GlobalNavigationSolution.c \
../dronecan/src/uavcan.protocol.AccessCommandShell_req.c \
../dronecan/src/uavcan.protocol.AccessCommandShell_res.c \
../dronecan/src/uavcan.protocol.CANIfaceStats.c \
../dronecan/src/uavcan.protocol.DataTypeKind.c \
../dronecan/src/uavcan.protocol.GetDataTypeInfo_req.c \
../dronecan/src/uavcan.protocol.GetDataTypeInfo_res.c \
../dronecan/src/uavcan.protocol.GetNodeInfo_req.c \
../dronecan/src/uavcan.protocol.GetNodeInfo_res.c \
../dronecan/src/uavcan.protocol.GetTransportStats_req.c \
../dronecan/src/uavcan.protocol.GetTransportStats_res.c \
../dronecan/src/uavcan.protocol.GlobalTimeSync.c \
../dronecan/src/uavcan.protocol.HardwareVersion.c \
../dronecan/src/uavcan.protocol.NodeStatus.c \
../dronecan/src/uavcan.protocol.Panic.c \
../dronecan/src/uavcan.protocol.RestartNode_req.c \
../dronecan/src/uavcan.protocol.RestartNode_res.c \
../dronecan/src/uavcan.protocol.SoftwareVersion.c \
../dronecan/src/uavcan.protocol.debug.KeyValue.c \
../dronecan/src/uavcan.protocol.debug.LogLevel.c \
../dronecan/src/uavcan.protocol.debug.LogMessage.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.c \
../dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.c \
../dronecan/src/uavcan.protocol.enumeration.Begin_req.c \
../dronecan/src/uavcan.protocol.enumeration.Begin_res.c \
../dronecan/src/uavcan.protocol.enumeration.Indication.c \
../dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.c \
../dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.c \
../dronecan/src/uavcan.protocol.file.Delete_req.c \
../dronecan/src/uavcan.protocol.file.Delete_res.c \
../dronecan/src/uavcan.protocol.file.EntryType.c \
../dronecan/src/uavcan.protocol.file.Error.c \
../dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.c \
../dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.c \
../dronecan/src/uavcan.protocol.file.GetInfo_req.c \
../dronecan/src/uavcan.protocol.file.GetInfo_res.c \
../dronecan/src/uavcan.protocol.file.Path.c \
../dronecan/src/uavcan.protocol.file.Read_req.c \
../dronecan/src/uavcan.protocol.file.Read_res.c \
../dronecan/src/uavcan.protocol.file.Write_req.c \
../dronecan/src/uavcan.protocol.file.Write_res.c \
../dronecan/src/uavcan.protocol.param.Empty.c \
../dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.c \
../dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.c \
../dronecan/src/uavcan.protocol.param.GetSet_req.c \
../dronecan/src/uavcan.protocol.param.GetSet_res.c \
../dronecan/src/uavcan.protocol.param.NumericValue.c \
../dronecan/src/uavcan.protocol.param.Value.c \
../dronecan/src/uavcan.tunnel.Broadcast.c \
../dronecan/src/uavcan.tunnel.Call_req.c \
../dronecan/src/uavcan.tunnel.Call_res.c \
../dronecan/src/uavcan.tunnel.Protocol.c \
../dronecan/src/uavcan.tunnel.SerialConfig.c \
../dronecan/src/uavcan.tunnel.Targetted.c 

OBJS += \
./dronecan/src/dronecan.protocol.CanStats.o \
./dronecan/src/dronecan.protocol.FlexDebug.o \
./dronecan/src/dronecan.protocol.Stats.o \
./dronecan/src/dronecan.remoteid.ArmStatus.o \
./dronecan/src/dronecan.remoteid.BasicID.o \
./dronecan/src/dronecan.remoteid.Location.o \
./dronecan/src/dronecan.remoteid.OperatorID.o \
./dronecan/src/dronecan.remoteid.SecureCommand_req.o \
./dronecan/src/dronecan.remoteid.SecureCommand_res.o \
./dronecan/src/dronecan.remoteid.SelfID.o \
./dronecan/src/dronecan.remoteid.System.o \
./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.o \
./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o \
./dronecan/src/dronecan.sensors.rc.RCInput.o \
./dronecan/src/dronecan.sensors.rpm.RPM.o \
./dronecan/src/uavcan.CoarseOrientation.o \
./dronecan/src/uavcan.Timestamp.o \
./dronecan/src/uavcan.equipment.actuator.ArrayCommand.o \
./dronecan/src/uavcan.equipment.actuator.Command.o \
./dronecan/src/uavcan.equipment.actuator.Status.o \
./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.o \
./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./dronecan/src/uavcan.equipment.ahrs.RawIMU.o \
./dronecan/src/uavcan.equipment.ahrs.Solution.o \
./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.o \
./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.o \
./dronecan/src/uavcan.equipment.air_data.RawAirData.o \
./dronecan/src/uavcan.equipment.air_data.Sideslip.o \
./dronecan/src/uavcan.equipment.air_data.StaticPressure.o \
./dronecan/src/uavcan.equipment.air_data.StaticTemperature.o \
./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.o \
./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.o \
./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o \
./dronecan/src/uavcan.equipment.camera_gimbal.Mode.o \
./dronecan/src/uavcan.equipment.camera_gimbal.Status.o \
./dronecan/src/uavcan.equipment.device.Temperature.o \
./dronecan/src/uavcan.equipment.esc.RPMCommand.o \
./dronecan/src/uavcan.equipment.esc.RawCommand.o \
./dronecan/src/uavcan.equipment.esc.Status.o \
./dronecan/src/uavcan.equipment.esc.StatusExtended.o \
./dronecan/src/uavcan.equipment.gnss.Auxiliary.o \
./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.o \
./dronecan/src/uavcan.equipment.gnss.Fix.o \
./dronecan/src/uavcan.equipment.gnss.Fix2.o \
./dronecan/src/uavcan.equipment.gnss.RTCMStream.o \
./dronecan/src/uavcan.equipment.hardpoint.Command.o \
./dronecan/src/uavcan.equipment.hardpoint.Status.o \
./dronecan/src/uavcan.equipment.ice.FuelTankStatus.o \
./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./dronecan/src/uavcan.equipment.ice.reciprocating.Status.o \
./dronecan/src/uavcan.equipment.indication.BeepCommand.o \
./dronecan/src/uavcan.equipment.indication.LightsCommand.o \
./dronecan/src/uavcan.equipment.indication.RGB565.o \
./dronecan/src/uavcan.equipment.indication.SingleLightCommand.o \
./dronecan/src/uavcan.equipment.power.BatteryInfo.o \
./dronecan/src/uavcan.equipment.power.CircuitStatus.o \
./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./dronecan/src/uavcan.equipment.range_sensor.Measurement.o \
./dronecan/src/uavcan.equipment.safety.ArmingStatus.o \
./dronecan/src/uavcan.navigation.GlobalNavigationSolution.o \
./dronecan/src/uavcan.protocol.AccessCommandShell_req.o \
./dronecan/src/uavcan.protocol.AccessCommandShell_res.o \
./dronecan/src/uavcan.protocol.CANIfaceStats.o \
./dronecan/src/uavcan.protocol.DataTypeKind.o \
./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.o \
./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.o \
./dronecan/src/uavcan.protocol.GetNodeInfo_req.o \
./dronecan/src/uavcan.protocol.GetNodeInfo_res.o \
./dronecan/src/uavcan.protocol.GetTransportStats_req.o \
./dronecan/src/uavcan.protocol.GetTransportStats_res.o \
./dronecan/src/uavcan.protocol.GlobalTimeSync.o \
./dronecan/src/uavcan.protocol.HardwareVersion.o \
./dronecan/src/uavcan.protocol.NodeStatus.o \
./dronecan/src/uavcan.protocol.Panic.o \
./dronecan/src/uavcan.protocol.RestartNode_req.o \
./dronecan/src/uavcan.protocol.RestartNode_res.o \
./dronecan/src/uavcan.protocol.SoftwareVersion.o \
./dronecan/src/uavcan.protocol.debug.KeyValue.o \
./dronecan/src/uavcan.protocol.debug.LogLevel.o \
./dronecan/src/uavcan.protocol.debug.LogMessage.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o \
./dronecan/src/uavcan.protocol.enumeration.Begin_req.o \
./dronecan/src/uavcan.protocol.enumeration.Begin_res.o \
./dronecan/src/uavcan.protocol.enumeration.Indication.o \
./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o \
./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o \
./dronecan/src/uavcan.protocol.file.Delete_req.o \
./dronecan/src/uavcan.protocol.file.Delete_res.o \
./dronecan/src/uavcan.protocol.file.EntryType.o \
./dronecan/src/uavcan.protocol.file.Error.o \
./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o \
./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o \
./dronecan/src/uavcan.protocol.file.GetInfo_req.o \
./dronecan/src/uavcan.protocol.file.GetInfo_res.o \
./dronecan/src/uavcan.protocol.file.Path.o \
./dronecan/src/uavcan.protocol.file.Read_req.o \
./dronecan/src/uavcan.protocol.file.Read_res.o \
./dronecan/src/uavcan.protocol.file.Write_req.o \
./dronecan/src/uavcan.protocol.file.Write_res.o \
./dronecan/src/uavcan.protocol.param.Empty.o \
./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.o \
./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.o \
./dronecan/src/uavcan.protocol.param.GetSet_req.o \
./dronecan/src/uavcan.protocol.param.GetSet_res.o \
./dronecan/src/uavcan.protocol.param.NumericValue.o \
./dronecan/src/uavcan.protocol.param.Value.o \
./dronecan/src/uavcan.tunnel.Broadcast.o \
./dronecan/src/uavcan.tunnel.Call_req.o \
./dronecan/src/uavcan.tunnel.Call_res.o \
./dronecan/src/uavcan.tunnel.Protocol.o \
./dronecan/src/uavcan.tunnel.SerialConfig.o \
./dronecan/src/uavcan.tunnel.Targetted.o 

C_DEPS += \
./dronecan/src/dronecan.protocol.CanStats.d \
./dronecan/src/dronecan.protocol.FlexDebug.d \
./dronecan/src/dronecan.protocol.Stats.d \
./dronecan/src/dronecan.remoteid.ArmStatus.d \
./dronecan/src/dronecan.remoteid.BasicID.d \
./dronecan/src/dronecan.remoteid.Location.d \
./dronecan/src/dronecan.remoteid.OperatorID.d \
./dronecan/src/dronecan.remoteid.SecureCommand_req.d \
./dronecan/src/dronecan.remoteid.SecureCommand_res.d \
./dronecan/src/dronecan.remoteid.SelfID.d \
./dronecan/src/dronecan.remoteid.System.d \
./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.d \
./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d \
./dronecan/src/dronecan.sensors.rc.RCInput.d \
./dronecan/src/dronecan.sensors.rpm.RPM.d \
./dronecan/src/uavcan.CoarseOrientation.d \
./dronecan/src/uavcan.Timestamp.d \
./dronecan/src/uavcan.equipment.actuator.ArrayCommand.d \
./dronecan/src/uavcan.equipment.actuator.Command.d \
./dronecan/src/uavcan.equipment.actuator.Status.d \
./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.d \
./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./dronecan/src/uavcan.equipment.ahrs.RawIMU.d \
./dronecan/src/uavcan.equipment.ahrs.Solution.d \
./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.d \
./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.d \
./dronecan/src/uavcan.equipment.air_data.RawAirData.d \
./dronecan/src/uavcan.equipment.air_data.Sideslip.d \
./dronecan/src/uavcan.equipment.air_data.StaticPressure.d \
./dronecan/src/uavcan.equipment.air_data.StaticTemperature.d \
./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.d \
./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.d \
./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d \
./dronecan/src/uavcan.equipment.camera_gimbal.Mode.d \
./dronecan/src/uavcan.equipment.camera_gimbal.Status.d \
./dronecan/src/uavcan.equipment.device.Temperature.d \
./dronecan/src/uavcan.equipment.esc.RPMCommand.d \
./dronecan/src/uavcan.equipment.esc.RawCommand.d \
./dronecan/src/uavcan.equipment.esc.Status.d \
./dronecan/src/uavcan.equipment.esc.StatusExtended.d \
./dronecan/src/uavcan.equipment.gnss.Auxiliary.d \
./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.d \
./dronecan/src/uavcan.equipment.gnss.Fix.d \
./dronecan/src/uavcan.equipment.gnss.Fix2.d \
./dronecan/src/uavcan.equipment.gnss.RTCMStream.d \
./dronecan/src/uavcan.equipment.hardpoint.Command.d \
./dronecan/src/uavcan.equipment.hardpoint.Status.d \
./dronecan/src/uavcan.equipment.ice.FuelTankStatus.d \
./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./dronecan/src/uavcan.equipment.ice.reciprocating.Status.d \
./dronecan/src/uavcan.equipment.indication.BeepCommand.d \
./dronecan/src/uavcan.equipment.indication.LightsCommand.d \
./dronecan/src/uavcan.equipment.indication.RGB565.d \
./dronecan/src/uavcan.equipment.indication.SingleLightCommand.d \
./dronecan/src/uavcan.equipment.power.BatteryInfo.d \
./dronecan/src/uavcan.equipment.power.CircuitStatus.d \
./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./dronecan/src/uavcan.equipment.range_sensor.Measurement.d \
./dronecan/src/uavcan.equipment.safety.ArmingStatus.d \
./dronecan/src/uavcan.navigation.GlobalNavigationSolution.d \
./dronecan/src/uavcan.protocol.AccessCommandShell_req.d \
./dronecan/src/uavcan.protocol.AccessCommandShell_res.d \
./dronecan/src/uavcan.protocol.CANIfaceStats.d \
./dronecan/src/uavcan.protocol.DataTypeKind.d \
./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.d \
./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.d \
./dronecan/src/uavcan.protocol.GetNodeInfo_req.d \
./dronecan/src/uavcan.protocol.GetNodeInfo_res.d \
./dronecan/src/uavcan.protocol.GetTransportStats_req.d \
./dronecan/src/uavcan.protocol.GetTransportStats_res.d \
./dronecan/src/uavcan.protocol.GlobalTimeSync.d \
./dronecan/src/uavcan.protocol.HardwareVersion.d \
./dronecan/src/uavcan.protocol.NodeStatus.d \
./dronecan/src/uavcan.protocol.Panic.d \
./dronecan/src/uavcan.protocol.RestartNode_req.d \
./dronecan/src/uavcan.protocol.RestartNode_res.d \
./dronecan/src/uavcan.protocol.SoftwareVersion.d \
./dronecan/src/uavcan.protocol.debug.KeyValue.d \
./dronecan/src/uavcan.protocol.debug.LogLevel.d \
./dronecan/src/uavcan.protocol.debug.LogMessage.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d \
./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d \
./dronecan/src/uavcan.protocol.enumeration.Begin_req.d \
./dronecan/src/uavcan.protocol.enumeration.Begin_res.d \
./dronecan/src/uavcan.protocol.enumeration.Indication.d \
./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d \
./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d \
./dronecan/src/uavcan.protocol.file.Delete_req.d \
./dronecan/src/uavcan.protocol.file.Delete_res.d \
./dronecan/src/uavcan.protocol.file.EntryType.d \
./dronecan/src/uavcan.protocol.file.Error.d \
./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d \
./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d \
./dronecan/src/uavcan.protocol.file.GetInfo_req.d \
./dronecan/src/uavcan.protocol.file.GetInfo_res.d \
./dronecan/src/uavcan.protocol.file.Path.d \
./dronecan/src/uavcan.protocol.file.Read_req.d \
./dronecan/src/uavcan.protocol.file.Read_res.d \
./dronecan/src/uavcan.protocol.file.Write_req.d \
./dronecan/src/uavcan.protocol.file.Write_res.d \
./dronecan/src/uavcan.protocol.param.Empty.d \
./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.d \
./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.d \
./dronecan/src/uavcan.protocol.param.GetSet_req.d \
./dronecan/src/uavcan.protocol.param.GetSet_res.d \
./dronecan/src/uavcan.protocol.param.NumericValue.d \
./dronecan/src/uavcan.protocol.param.Value.d \
./dronecan/src/uavcan.tunnel.Broadcast.d \
./dronecan/src/uavcan.tunnel.Call_req.d \
./dronecan/src/uavcan.tunnel.Call_res.d \
./dronecan/src/uavcan.tunnel.Protocol.d \
./dronecan/src/uavcan.tunnel.SerialConfig.d \
./dronecan/src/uavcan.tunnel.Targetted.d 


# Each subdirectory must supply rules for building sources it contributes
dronecan/src/%.o dronecan/src/%.su dronecan/src/%.cyclo: ../dronecan/src/%.c dronecan/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G474xx -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I"/home/terapat/STM32CubeIDE/workspace_1.19.0/g474_uavcan/libcanard" -I"/home/terapat/STM32CubeIDE/workspace_1.19.0/g474_uavcan/dronecan/include" -I"/home/terapat/STM32CubeIDE/workspace_1.19.0/g474_uavcan/dronecan/src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-dronecan-2f-src

clean-dronecan-2f-src:
	-$(RM) ./dronecan/src/dronecan.protocol.CanStats.cyclo ./dronecan/src/dronecan.protocol.CanStats.d ./dronecan/src/dronecan.protocol.CanStats.o ./dronecan/src/dronecan.protocol.CanStats.su ./dronecan/src/dronecan.protocol.FlexDebug.cyclo ./dronecan/src/dronecan.protocol.FlexDebug.d ./dronecan/src/dronecan.protocol.FlexDebug.o ./dronecan/src/dronecan.protocol.FlexDebug.su ./dronecan/src/dronecan.protocol.Stats.cyclo ./dronecan/src/dronecan.protocol.Stats.d ./dronecan/src/dronecan.protocol.Stats.o ./dronecan/src/dronecan.protocol.Stats.su ./dronecan/src/dronecan.remoteid.ArmStatus.cyclo ./dronecan/src/dronecan.remoteid.ArmStatus.d ./dronecan/src/dronecan.remoteid.ArmStatus.o ./dronecan/src/dronecan.remoteid.ArmStatus.su ./dronecan/src/dronecan.remoteid.BasicID.cyclo ./dronecan/src/dronecan.remoteid.BasicID.d ./dronecan/src/dronecan.remoteid.BasicID.o ./dronecan/src/dronecan.remoteid.BasicID.su ./dronecan/src/dronecan.remoteid.Location.cyclo ./dronecan/src/dronecan.remoteid.Location.d ./dronecan/src/dronecan.remoteid.Location.o ./dronecan/src/dronecan.remoteid.Location.su ./dronecan/src/dronecan.remoteid.OperatorID.cyclo ./dronecan/src/dronecan.remoteid.OperatorID.d ./dronecan/src/dronecan.remoteid.OperatorID.o ./dronecan/src/dronecan.remoteid.OperatorID.su ./dronecan/src/dronecan.remoteid.SecureCommand_req.cyclo ./dronecan/src/dronecan.remoteid.SecureCommand_req.d ./dronecan/src/dronecan.remoteid.SecureCommand_req.o ./dronecan/src/dronecan.remoteid.SecureCommand_req.su ./dronecan/src/dronecan.remoteid.SecureCommand_res.cyclo ./dronecan/src/dronecan.remoteid.SecureCommand_res.d ./dronecan/src/dronecan.remoteid.SecureCommand_res.o ./dronecan/src/dronecan.remoteid.SecureCommand_res.su ./dronecan/src/dronecan.remoteid.SelfID.cyclo ./dronecan/src/dronecan.remoteid.SelfID.d ./dronecan/src/dronecan.remoteid.SelfID.o ./dronecan/src/dronecan.remoteid.SelfID.su ./dronecan/src/dronecan.remoteid.System.cyclo ./dronecan/src/dronecan.remoteid.System.d ./dronecan/src/dronecan.remoteid.System.o ./dronecan/src/dronecan.remoteid.System.su ./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.cyclo ./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.d ./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.o ./dronecan/src/dronecan.sensors.hygrometer.Hygrometer.su ./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.cyclo ./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d ./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o ./dronecan/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.su ./dronecan/src/dronecan.sensors.rc.RCInput.cyclo ./dronecan/src/dronecan.sensors.rc.RCInput.d ./dronecan/src/dronecan.sensors.rc.RCInput.o ./dronecan/src/dronecan.sensors.rc.RCInput.su ./dronecan/src/dronecan.sensors.rpm.RPM.cyclo ./dronecan/src/dronecan.sensors.rpm.RPM.d ./dronecan/src/dronecan.sensors.rpm.RPM.o ./dronecan/src/dronecan.sensors.rpm.RPM.su ./dronecan/src/uavcan.CoarseOrientation.cyclo ./dronecan/src/uavcan.CoarseOrientation.d ./dronecan/src/uavcan.CoarseOrientation.o ./dronecan/src/uavcan.CoarseOrientation.su ./dronecan/src/uavcan.Timestamp.cyclo ./dronecan/src/uavcan.Timestamp.d ./dronecan/src/uavcan.Timestamp.o ./dronecan/src/uavcan.Timestamp.su ./dronecan/src/uavcan.equipment.actuator.ArrayCommand.cyclo ./dronecan/src/uavcan.equipment.actuator.ArrayCommand.d ./dronecan/src/uavcan.equipment.actuator.ArrayCommand.o ./dronecan/src/uavcan.equipment.actuator.ArrayCommand.su ./dronecan/src/uavcan.equipment.actuator.Command.cyclo ./dronecan/src/uavcan.equipment.actuator.Command.d ./dronecan/src/uavcan.equipment.actuator.Command.o ./dronecan/src/uavcan.equipment.actuator.Command.su ./dronecan/src/uavcan.equipment.actuator.Status.cyclo ./dronecan/src/uavcan.equipment.actuator.Status.d ./dronecan/src/uavcan.equipment.actuator.Status.o ./dronecan/src/uavcan.equipment.actuator.Status.su ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.d ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.o ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength.su ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o ./dronecan/src/uavcan.equipment.ahrs.MagneticFieldStrength2.su ./dronecan/src/uavcan.equipment.ahrs.RawIMU.cyclo ./dronecan/src/uavcan.equipment.ahrs.RawIMU.d ./dronecan/src/uavcan.equipment.ahrs.RawIMU.o ./dronecan/src/uavcan.equipment.ahrs.RawIMU.su ./dronecan/src/uavcan.equipment.ahrs.Solution.cyclo ./dronecan/src/uavcan.equipment.ahrs.Solution.d ./dronecan/src/uavcan.equipment.ahrs.Solution.o ./dronecan/src/uavcan.equipment.ahrs.Solution.su ./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.cyclo ./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.d ./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.o ./dronecan/src/uavcan.equipment.air_data.AngleOfAttack.su ./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.d ./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.o ./dronecan/src/uavcan.equipment.air_data.IndicatedAirspeed.su ./dronecan/src/uavcan.equipment.air_data.RawAirData.cyclo ./dronecan/src/uavcan.equipment.air_data.RawAirData.d ./dronecan/src/uavcan.equipment.air_data.RawAirData.o ./dronecan/src/uavcan.equipment.air_data.RawAirData.su ./dronecan/src/uavcan.equipment.air_data.Sideslip.cyclo ./dronecan/src/uavcan.equipment.air_data.Sideslip.d ./dronecan/src/uavcan.equipment.air_data.Sideslip.o ./dronecan/src/uavcan.equipment.air_data.Sideslip.su ./dronecan/src/uavcan.equipment.air_data.StaticPressure.cyclo ./dronecan/src/uavcan.equipment.air_data.StaticPressure.d ./dronecan/src/uavcan.equipment.air_data.StaticPressure.o ./dronecan/src/uavcan.equipment.air_data.StaticPressure.su
	-$(RM) ./dronecan/src/uavcan.equipment.air_data.StaticTemperature.cyclo ./dronecan/src/uavcan.equipment.air_data.StaticTemperature.d ./dronecan/src/uavcan.equipment.air_data.StaticTemperature.o ./dronecan/src/uavcan.equipment.air_data.StaticTemperature.su ./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.cyclo ./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.d ./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.o ./dronecan/src/uavcan.equipment.air_data.TrueAirspeed.su ./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.cyclo ./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.d ./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.o ./dronecan/src/uavcan.equipment.camera_gimbal.AngularCommand.su ./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.cyclo ./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.d ./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.o ./dronecan/src/uavcan.equipment.camera_gimbal.GEOPOICommand.su ./dronecan/src/uavcan.equipment.camera_gimbal.Mode.cyclo ./dronecan/src/uavcan.equipment.camera_gimbal.Mode.d ./dronecan/src/uavcan.equipment.camera_gimbal.Mode.o ./dronecan/src/uavcan.equipment.camera_gimbal.Mode.su ./dronecan/src/uavcan.equipment.camera_gimbal.Status.cyclo ./dronecan/src/uavcan.equipment.camera_gimbal.Status.d ./dronecan/src/uavcan.equipment.camera_gimbal.Status.o ./dronecan/src/uavcan.equipment.camera_gimbal.Status.su ./dronecan/src/uavcan.equipment.device.Temperature.cyclo ./dronecan/src/uavcan.equipment.device.Temperature.d ./dronecan/src/uavcan.equipment.device.Temperature.o ./dronecan/src/uavcan.equipment.device.Temperature.su ./dronecan/src/uavcan.equipment.esc.RPMCommand.cyclo ./dronecan/src/uavcan.equipment.esc.RPMCommand.d ./dronecan/src/uavcan.equipment.esc.RPMCommand.o ./dronecan/src/uavcan.equipment.esc.RPMCommand.su ./dronecan/src/uavcan.equipment.esc.RawCommand.cyclo ./dronecan/src/uavcan.equipment.esc.RawCommand.d ./dronecan/src/uavcan.equipment.esc.RawCommand.o ./dronecan/src/uavcan.equipment.esc.RawCommand.su ./dronecan/src/uavcan.equipment.esc.Status.cyclo ./dronecan/src/uavcan.equipment.esc.Status.d ./dronecan/src/uavcan.equipment.esc.Status.o ./dronecan/src/uavcan.equipment.esc.Status.su ./dronecan/src/uavcan.equipment.esc.StatusExtended.cyclo ./dronecan/src/uavcan.equipment.esc.StatusExtended.d ./dronecan/src/uavcan.equipment.esc.StatusExtended.o ./dronecan/src/uavcan.equipment.esc.StatusExtended.su ./dronecan/src/uavcan.equipment.gnss.Auxiliary.cyclo ./dronecan/src/uavcan.equipment.gnss.Auxiliary.d ./dronecan/src/uavcan.equipment.gnss.Auxiliary.o ./dronecan/src/uavcan.equipment.gnss.Auxiliary.su ./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.d ./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.o ./dronecan/src/uavcan.equipment.gnss.ECEFPositionVelocity.su ./dronecan/src/uavcan.equipment.gnss.Fix.cyclo ./dronecan/src/uavcan.equipment.gnss.Fix.d ./dronecan/src/uavcan.equipment.gnss.Fix.o ./dronecan/src/uavcan.equipment.gnss.Fix.su ./dronecan/src/uavcan.equipment.gnss.Fix2.cyclo ./dronecan/src/uavcan.equipment.gnss.Fix2.d ./dronecan/src/uavcan.equipment.gnss.Fix2.o ./dronecan/src/uavcan.equipment.gnss.Fix2.su ./dronecan/src/uavcan.equipment.gnss.RTCMStream.cyclo ./dronecan/src/uavcan.equipment.gnss.RTCMStream.d ./dronecan/src/uavcan.equipment.gnss.RTCMStream.o ./dronecan/src/uavcan.equipment.gnss.RTCMStream.su ./dronecan/src/uavcan.equipment.hardpoint.Command.cyclo ./dronecan/src/uavcan.equipment.hardpoint.Command.d ./dronecan/src/uavcan.equipment.hardpoint.Command.o ./dronecan/src/uavcan.equipment.hardpoint.Command.su ./dronecan/src/uavcan.equipment.hardpoint.Status.cyclo ./dronecan/src/uavcan.equipment.hardpoint.Status.d ./dronecan/src/uavcan.equipment.hardpoint.Status.o ./dronecan/src/uavcan.equipment.hardpoint.Status.su ./dronecan/src/uavcan.equipment.ice.FuelTankStatus.cyclo ./dronecan/src/uavcan.equipment.ice.FuelTankStatus.d ./dronecan/src/uavcan.equipment.ice.FuelTankStatus.o ./dronecan/src/uavcan.equipment.ice.FuelTankStatus.su ./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d ./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o ./dronecan/src/uavcan.equipment.ice.reciprocating.CylinderStatus.su ./dronecan/src/uavcan.equipment.ice.reciprocating.Status.cyclo ./dronecan/src/uavcan.equipment.ice.reciprocating.Status.d ./dronecan/src/uavcan.equipment.ice.reciprocating.Status.o ./dronecan/src/uavcan.equipment.ice.reciprocating.Status.su ./dronecan/src/uavcan.equipment.indication.BeepCommand.cyclo ./dronecan/src/uavcan.equipment.indication.BeepCommand.d ./dronecan/src/uavcan.equipment.indication.BeepCommand.o ./dronecan/src/uavcan.equipment.indication.BeepCommand.su ./dronecan/src/uavcan.equipment.indication.LightsCommand.cyclo ./dronecan/src/uavcan.equipment.indication.LightsCommand.d ./dronecan/src/uavcan.equipment.indication.LightsCommand.o ./dronecan/src/uavcan.equipment.indication.LightsCommand.su ./dronecan/src/uavcan.equipment.indication.RGB565.cyclo ./dronecan/src/uavcan.equipment.indication.RGB565.d ./dronecan/src/uavcan.equipment.indication.RGB565.o ./dronecan/src/uavcan.equipment.indication.RGB565.su ./dronecan/src/uavcan.equipment.indication.SingleLightCommand.cyclo ./dronecan/src/uavcan.equipment.indication.SingleLightCommand.d ./dronecan/src/uavcan.equipment.indication.SingleLightCommand.o ./dronecan/src/uavcan.equipment.indication.SingleLightCommand.su ./dronecan/src/uavcan.equipment.power.BatteryInfo.cyclo ./dronecan/src/uavcan.equipment.power.BatteryInfo.d ./dronecan/src/uavcan.equipment.power.BatteryInfo.o ./dronecan/src/uavcan.equipment.power.BatteryInfo.su ./dronecan/src/uavcan.equipment.power.CircuitStatus.cyclo ./dronecan/src/uavcan.equipment.power.CircuitStatus.d ./dronecan/src/uavcan.equipment.power.CircuitStatus.o
	-$(RM) ./dronecan/src/uavcan.equipment.power.CircuitStatus.su ./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./dronecan/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.su ./dronecan/src/uavcan.equipment.range_sensor.Measurement.cyclo ./dronecan/src/uavcan.equipment.range_sensor.Measurement.d ./dronecan/src/uavcan.equipment.range_sensor.Measurement.o ./dronecan/src/uavcan.equipment.range_sensor.Measurement.su ./dronecan/src/uavcan.equipment.safety.ArmingStatus.cyclo ./dronecan/src/uavcan.equipment.safety.ArmingStatus.d ./dronecan/src/uavcan.equipment.safety.ArmingStatus.o ./dronecan/src/uavcan.equipment.safety.ArmingStatus.su ./dronecan/src/uavcan.navigation.GlobalNavigationSolution.cyclo ./dronecan/src/uavcan.navigation.GlobalNavigationSolution.d ./dronecan/src/uavcan.navigation.GlobalNavigationSolution.o ./dronecan/src/uavcan.navigation.GlobalNavigationSolution.su ./dronecan/src/uavcan.protocol.AccessCommandShell_req.cyclo ./dronecan/src/uavcan.protocol.AccessCommandShell_req.d ./dronecan/src/uavcan.protocol.AccessCommandShell_req.o ./dronecan/src/uavcan.protocol.AccessCommandShell_req.su ./dronecan/src/uavcan.protocol.AccessCommandShell_res.cyclo ./dronecan/src/uavcan.protocol.AccessCommandShell_res.d ./dronecan/src/uavcan.protocol.AccessCommandShell_res.o ./dronecan/src/uavcan.protocol.AccessCommandShell_res.su ./dronecan/src/uavcan.protocol.CANIfaceStats.cyclo ./dronecan/src/uavcan.protocol.CANIfaceStats.d ./dronecan/src/uavcan.protocol.CANIfaceStats.o ./dronecan/src/uavcan.protocol.CANIfaceStats.su ./dronecan/src/uavcan.protocol.DataTypeKind.cyclo ./dronecan/src/uavcan.protocol.DataTypeKind.d ./dronecan/src/uavcan.protocol.DataTypeKind.o ./dronecan/src/uavcan.protocol.DataTypeKind.su ./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.cyclo ./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.d ./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.o ./dronecan/src/uavcan.protocol.GetDataTypeInfo_req.su ./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.cyclo ./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.d ./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.o ./dronecan/src/uavcan.protocol.GetDataTypeInfo_res.su ./dronecan/src/uavcan.protocol.GetNodeInfo_req.cyclo ./dronecan/src/uavcan.protocol.GetNodeInfo_req.d ./dronecan/src/uavcan.protocol.GetNodeInfo_req.o ./dronecan/src/uavcan.protocol.GetNodeInfo_req.su ./dronecan/src/uavcan.protocol.GetNodeInfo_res.cyclo ./dronecan/src/uavcan.protocol.GetNodeInfo_res.d ./dronecan/src/uavcan.protocol.GetNodeInfo_res.o ./dronecan/src/uavcan.protocol.GetNodeInfo_res.su ./dronecan/src/uavcan.protocol.GetTransportStats_req.cyclo ./dronecan/src/uavcan.protocol.GetTransportStats_req.d ./dronecan/src/uavcan.protocol.GetTransportStats_req.o ./dronecan/src/uavcan.protocol.GetTransportStats_req.su ./dronecan/src/uavcan.protocol.GetTransportStats_res.cyclo ./dronecan/src/uavcan.protocol.GetTransportStats_res.d ./dronecan/src/uavcan.protocol.GetTransportStats_res.o ./dronecan/src/uavcan.protocol.GetTransportStats_res.su ./dronecan/src/uavcan.protocol.GlobalTimeSync.cyclo ./dronecan/src/uavcan.protocol.GlobalTimeSync.d ./dronecan/src/uavcan.protocol.GlobalTimeSync.o ./dronecan/src/uavcan.protocol.GlobalTimeSync.su ./dronecan/src/uavcan.protocol.HardwareVersion.cyclo ./dronecan/src/uavcan.protocol.HardwareVersion.d ./dronecan/src/uavcan.protocol.HardwareVersion.o ./dronecan/src/uavcan.protocol.HardwareVersion.su ./dronecan/src/uavcan.protocol.NodeStatus.cyclo ./dronecan/src/uavcan.protocol.NodeStatus.d ./dronecan/src/uavcan.protocol.NodeStatus.o ./dronecan/src/uavcan.protocol.NodeStatus.su ./dronecan/src/uavcan.protocol.Panic.cyclo ./dronecan/src/uavcan.protocol.Panic.d ./dronecan/src/uavcan.protocol.Panic.o ./dronecan/src/uavcan.protocol.Panic.su ./dronecan/src/uavcan.protocol.RestartNode_req.cyclo ./dronecan/src/uavcan.protocol.RestartNode_req.d ./dronecan/src/uavcan.protocol.RestartNode_req.o ./dronecan/src/uavcan.protocol.RestartNode_req.su ./dronecan/src/uavcan.protocol.RestartNode_res.cyclo ./dronecan/src/uavcan.protocol.RestartNode_res.d ./dronecan/src/uavcan.protocol.RestartNode_res.o ./dronecan/src/uavcan.protocol.RestartNode_res.su ./dronecan/src/uavcan.protocol.SoftwareVersion.cyclo ./dronecan/src/uavcan.protocol.SoftwareVersion.d ./dronecan/src/uavcan.protocol.SoftwareVersion.o ./dronecan/src/uavcan.protocol.SoftwareVersion.su ./dronecan/src/uavcan.protocol.debug.KeyValue.cyclo ./dronecan/src/uavcan.protocol.debug.KeyValue.d ./dronecan/src/uavcan.protocol.debug.KeyValue.o ./dronecan/src/uavcan.protocol.debug.KeyValue.su ./dronecan/src/uavcan.protocol.debug.LogLevel.cyclo ./dronecan/src/uavcan.protocol.debug.LogLevel.d ./dronecan/src/uavcan.protocol.debug.LogLevel.o ./dronecan/src/uavcan.protocol.debug.LogLevel.su ./dronecan/src/uavcan.protocol.debug.LogMessage.cyclo ./dronecan/src/uavcan.protocol.debug.LogMessage.d ./dronecan/src/uavcan.protocol.debug.LogMessage.o ./dronecan/src/uavcan.protocol.debug.LogMessage.su ./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.d ./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.o ./dronecan/src/uavcan.protocol.dynamic_node_id.Allocation.su ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.su ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.su
	-$(RM) ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Discovery.su ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.Entry.su ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.su ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.cyclo ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o ./dronecan/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.su ./dronecan/src/uavcan.protocol.enumeration.Begin_req.cyclo ./dronecan/src/uavcan.protocol.enumeration.Begin_req.d ./dronecan/src/uavcan.protocol.enumeration.Begin_req.o ./dronecan/src/uavcan.protocol.enumeration.Begin_req.su ./dronecan/src/uavcan.protocol.enumeration.Begin_res.cyclo ./dronecan/src/uavcan.protocol.enumeration.Begin_res.d ./dronecan/src/uavcan.protocol.enumeration.Begin_res.o ./dronecan/src/uavcan.protocol.enumeration.Begin_res.su ./dronecan/src/uavcan.protocol.enumeration.Indication.cyclo ./dronecan/src/uavcan.protocol.enumeration.Indication.d ./dronecan/src/uavcan.protocol.enumeration.Indication.o ./dronecan/src/uavcan.protocol.enumeration.Indication.su ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.cyclo ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_req.su ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.cyclo ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o ./dronecan/src/uavcan.protocol.file.BeginFirmwareUpdate_res.su ./dronecan/src/uavcan.protocol.file.Delete_req.cyclo ./dronecan/src/uavcan.protocol.file.Delete_req.d ./dronecan/src/uavcan.protocol.file.Delete_req.o ./dronecan/src/uavcan.protocol.file.Delete_req.su ./dronecan/src/uavcan.protocol.file.Delete_res.cyclo ./dronecan/src/uavcan.protocol.file.Delete_res.d ./dronecan/src/uavcan.protocol.file.Delete_res.o ./dronecan/src/uavcan.protocol.file.Delete_res.su ./dronecan/src/uavcan.protocol.file.EntryType.cyclo ./dronecan/src/uavcan.protocol.file.EntryType.d ./dronecan/src/uavcan.protocol.file.EntryType.o ./dronecan/src/uavcan.protocol.file.EntryType.su ./dronecan/src/uavcan.protocol.file.Error.cyclo ./dronecan/src/uavcan.protocol.file.Error.d ./dronecan/src/uavcan.protocol.file.Error.o ./dronecan/src/uavcan.protocol.file.Error.su ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.cyclo ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.su ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.cyclo ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o ./dronecan/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.su ./dronecan/src/uavcan.protocol.file.GetInfo_req.cyclo ./dronecan/src/uavcan.protocol.file.GetInfo_req.d ./dronecan/src/uavcan.protocol.file.GetInfo_req.o ./dronecan/src/uavcan.protocol.file.GetInfo_req.su ./dronecan/src/uavcan.protocol.file.GetInfo_res.cyclo ./dronecan/src/uavcan.protocol.file.GetInfo_res.d ./dronecan/src/uavcan.protocol.file.GetInfo_res.o ./dronecan/src/uavcan.protocol.file.GetInfo_res.su ./dronecan/src/uavcan.protocol.file.Path.cyclo ./dronecan/src/uavcan.protocol.file.Path.d ./dronecan/src/uavcan.protocol.file.Path.o ./dronecan/src/uavcan.protocol.file.Path.su ./dronecan/src/uavcan.protocol.file.Read_req.cyclo ./dronecan/src/uavcan.protocol.file.Read_req.d ./dronecan/src/uavcan.protocol.file.Read_req.o ./dronecan/src/uavcan.protocol.file.Read_req.su ./dronecan/src/uavcan.protocol.file.Read_res.cyclo ./dronecan/src/uavcan.protocol.file.Read_res.d ./dronecan/src/uavcan.protocol.file.Read_res.o ./dronecan/src/uavcan.protocol.file.Read_res.su ./dronecan/src/uavcan.protocol.file.Write_req.cyclo ./dronecan/src/uavcan.protocol.file.Write_req.d ./dronecan/src/uavcan.protocol.file.Write_req.o ./dronecan/src/uavcan.protocol.file.Write_req.su ./dronecan/src/uavcan.protocol.file.Write_res.cyclo ./dronecan/src/uavcan.protocol.file.Write_res.d ./dronecan/src/uavcan.protocol.file.Write_res.o ./dronecan/src/uavcan.protocol.file.Write_res.su ./dronecan/src/uavcan.protocol.param.Empty.cyclo ./dronecan/src/uavcan.protocol.param.Empty.d ./dronecan/src/uavcan.protocol.param.Empty.o ./dronecan/src/uavcan.protocol.param.Empty.su ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.cyclo ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.d ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.o ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_req.su ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.cyclo ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.d ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.o ./dronecan/src/uavcan.protocol.param.ExecuteOpcode_res.su ./dronecan/src/uavcan.protocol.param.GetSet_req.cyclo ./dronecan/src/uavcan.protocol.param.GetSet_req.d ./dronecan/src/uavcan.protocol.param.GetSet_req.o ./dronecan/src/uavcan.protocol.param.GetSet_req.su ./dronecan/src/uavcan.protocol.param.GetSet_res.cyclo ./dronecan/src/uavcan.protocol.param.GetSet_res.d ./dronecan/src/uavcan.protocol.param.GetSet_res.o
	-$(RM) ./dronecan/src/uavcan.protocol.param.GetSet_res.su ./dronecan/src/uavcan.protocol.param.NumericValue.cyclo ./dronecan/src/uavcan.protocol.param.NumericValue.d ./dronecan/src/uavcan.protocol.param.NumericValue.o ./dronecan/src/uavcan.protocol.param.NumericValue.su ./dronecan/src/uavcan.protocol.param.Value.cyclo ./dronecan/src/uavcan.protocol.param.Value.d ./dronecan/src/uavcan.protocol.param.Value.o ./dronecan/src/uavcan.protocol.param.Value.su ./dronecan/src/uavcan.tunnel.Broadcast.cyclo ./dronecan/src/uavcan.tunnel.Broadcast.d ./dronecan/src/uavcan.tunnel.Broadcast.o ./dronecan/src/uavcan.tunnel.Broadcast.su ./dronecan/src/uavcan.tunnel.Call_req.cyclo ./dronecan/src/uavcan.tunnel.Call_req.d ./dronecan/src/uavcan.tunnel.Call_req.o ./dronecan/src/uavcan.tunnel.Call_req.su ./dronecan/src/uavcan.tunnel.Call_res.cyclo ./dronecan/src/uavcan.tunnel.Call_res.d ./dronecan/src/uavcan.tunnel.Call_res.o ./dronecan/src/uavcan.tunnel.Call_res.su ./dronecan/src/uavcan.tunnel.Protocol.cyclo ./dronecan/src/uavcan.tunnel.Protocol.d ./dronecan/src/uavcan.tunnel.Protocol.o ./dronecan/src/uavcan.tunnel.Protocol.su ./dronecan/src/uavcan.tunnel.SerialConfig.cyclo ./dronecan/src/uavcan.tunnel.SerialConfig.d ./dronecan/src/uavcan.tunnel.SerialConfig.o ./dronecan/src/uavcan.tunnel.SerialConfig.su ./dronecan/src/uavcan.tunnel.Targetted.cyclo ./dronecan/src/uavcan.tunnel.Targetted.d ./dronecan/src/uavcan.tunnel.Targetted.o ./dronecan/src/uavcan.tunnel.Targetted.su

.PHONY: clean-dronecan-2f-src

